# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Install RxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Install RxSwift
  pod 'RxSwift', '~> 4.0'

end
