# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Share subscriptions' do

  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'

end
